pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'make
                '
            }

        stage('Test') {
            steps {
                sh 'make check'
            }
        }
        stage('Deploy') {
            when { tag "release-*" }
            steps {
                echo 'Deploying only because this commit is tagged...'
                sh 'make deploy'
            }
        }
    }
}